@startuml

[Service] as MapperService
' ...
[**UserActiveRecord**] as MapperComponent #Khaki
database "**Database**" as MapperDatabase #Khaki {
}

MapperService .up.> MapperComponent
' ...
MapperComponent .right.> MapperDatabase

note top of MapperComponent: ドメインロジック

@enduml
